CREATE SEQUENCE SEQ_LQ_BC_REQ_PK
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_LQ_BC_REQ_HIS_PK
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE LQ_BUSINESS_COUPON_REQUEST (
    REQUEST_ID               NUMBER PRIMARY KEY,
    BUSINESS_ID              NUMBER NOT NULL,
    LOCATION_ID              NUMBER NOT NULL,
    ADMIN_USER_ID            NUMBER NOT NULL,
    COUPON_NAME              VARCHAR2(100) NOT NULL,
    COUPON_DESCRIPTION       VARCHAR2(1000),
    PRICE_POINT              NUMBER NOT NULL,
    STOCK                    NUMBER DEFAULT 0 NOT NULL,
    TARGET_STATUS            VARCHAR2(20) DEFAULT 'ON_SALE' NOT NULL,
    REQUEST_STATUS           VARCHAR2(20) DEFAULT 'REQUESTED' NOT NULL,
    REQUEST_VERSION          NUMBER DEFAULT 1 NOT NULL,
    LAST_HOLD_REASON         VARCHAR2(1000),
    APPROVED_REWARD_ITEM_ID  NUMBER,
    REQUESTED_AT             DATE DEFAULT SYSDATE NOT NULL,
    RESPONDED_AT             DATE,
    CREATED_AT               DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT               DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_BC_REQ_BIZ
        FOREIGN KEY (BUSINESS_ID) REFERENCES LQ_BUSINESS(BUSINESS_ID),
    CONSTRAINT FK_LQ_BC_REQ_LOC
        FOREIGN KEY (LOCATION_ID) REFERENCES LQ_LOCATION(LOCATION_ID),
    CONSTRAINT FK_LQ_BC_REQ_ADM
        FOREIGN KEY (ADMIN_USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT FK_LQ_BC_REQ_APP_RI
        FOREIGN KEY (APPROVED_REWARD_ITEM_ID) REFERENCES LQ_REWARD_ITEM(REWARD_ITEM_ID),
    CONSTRAINT CHK_LQ_BC_REQ_PRICE
        CHECK (PRICE_POINT >= 0),
    CONSTRAINT CHK_LQ_BC_REQ_STOCK
        CHECK (STOCK >= 0),
    CONSTRAINT CHK_LQ_BC_REQ_TGT_ST
        CHECK (TARGET_STATUS IN ('ON_SALE', 'SOLD_OUT', 'HIDDEN')),
    CONSTRAINT CHK_LQ_BC_REQ_STATUS
        CHECK (REQUEST_STATUS IN ('REQUESTED', 'HOLD', 'ACCEPTED', 'CANCELLED')),
    CONSTRAINT CHK_LQ_BC_REQ_VER
        CHECK (REQUEST_VERSION >= 1)
);

CREATE INDEX IDX_LQ_BC_REQ_STATUS
ON LQ_BUSINESS_COUPON_REQUEST (REQUEST_STATUS);

CREATE INDEX IDX_LQ_BC_REQ_BIZ
ON LQ_BUSINESS_COUPON_REQUEST (BUSINESS_ID);

CREATE INDEX IDX_LQ_BC_REQ_LOC
ON LQ_BUSINESS_COUPON_REQUEST (LOCATION_ID);

CREATE INDEX IDX_LQ_BC_REQ_ADM
ON LQ_BUSINESS_COUPON_REQUEST (ADMIN_USER_ID);

CREATE TABLE LQ_BUSINESS_COUPON_REQ_HIST (
    HISTORY_ID               NUMBER PRIMARY KEY,
    REQUEST_ID               NUMBER NOT NULL,
    ACTION_TYPE              VARCHAR2(30) NOT NULL,
    ACTION_ROLE              VARCHAR2(20) NOT NULL,
    ACTION_BY_USER_ID        NUMBER,
    REQUEST_VERSION          NUMBER DEFAULT 1 NOT NULL,
    COMMENT_TEXT             VARCHAR2(1000),
    SNAPSHOT_COUPON_NAME     VARCHAR2(100),
    SNAPSHOT_COUPON_DESC     VARCHAR2(1000),
    SNAPSHOT_PRICE_POINT     NUMBER,
    SNAPSHOT_STOCK           NUMBER,
    SNAPSHOT_TARGET_STATUS   VARCHAR2(20),
    CREATED_AT               DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_BC_H_REQ
        FOREIGN KEY (REQUEST_ID) REFERENCES LQ_BUSINESS_COUPON_REQUEST(REQUEST_ID),
    CONSTRAINT FK_LQ_BC_H_USER
        FOREIGN KEY (ACTION_BY_USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT CHK_LQ_BC_H_ROLE
        CHECK (ACTION_ROLE IN ('ADMIN', 'BUSINESS', 'SYSTEM')),
    CONSTRAINT CHK_LQ_BC_H_TYPE
        CHECK (ACTION_TYPE IN ('CREATED', 'UPDATED', 'RESUBMITTED', 'HOLD', 'ACCEPTED', 'CANCELLED')),
    CONSTRAINT CHK_LQ_BC_H_VER
        CHECK (REQUEST_VERSION >= 1),
    CONSTRAINT CHK_LQ_BC_H_TGT_ST
        CHECK (SNAPSHOT_TARGET_STATUS IS NULL OR SNAPSHOT_TARGET_STATUS IN ('ON_SALE', 'SOLD_OUT', 'HIDDEN'))
);

CREATE INDEX IDX_LQ_BC_H_REQ
ON LQ_BUSINESS_COUPON_REQ_HIST (REQUEST_ID);

ALTER TABLE LQ_REWARD_ITEM ADD (
    LOCATION_ID    NUMBER,
    REQUEST_ID     NUMBER,
    COUPON_SCOPE   VARCHAR2(20)
);

UPDATE LQ_REWARD_ITEM
SET COUPON_SCOPE = 'GENERAL'
WHERE COUPON_SCOPE IS NULL;

ALTER TABLE LQ_REWARD_ITEM
MODIFY COUPON_SCOPE VARCHAR2(20) DEFAULT 'GENERAL' NOT NULL;

ALTER TABLE LQ_REWARD_ITEM
ADD CONSTRAINT FK_LQ_RI_LOC
FOREIGN KEY (LOCATION_ID) REFERENCES LQ_LOCATION(LOCATION_ID);

ALTER TABLE LQ_REWARD_ITEM
ADD CONSTRAINT FK_LQ_RI_REQ
FOREIGN KEY (REQUEST_ID) REFERENCES LQ_BUSINESS_COUPON_REQUEST(REQUEST_ID);

ALTER TABLE LQ_REWARD_ITEM
ADD CONSTRAINT UQ_LQ_RI_REQ_ID
UNIQUE (REQUEST_ID);

ALTER TABLE LQ_REWARD_ITEM
ADD CONSTRAINT CHK_LQ_RI_SCOPE
CHECK (COUPON_SCOPE IN ('GENERAL', 'BUSINESS_LOCATION'));

CREATE INDEX IDX_LQ_RI_LOC
ON LQ_REWARD_ITEM (LOCATION_ID);

COMMIT;
