-- 자식 테이블부터 삭제
DROP TABLE LQ_USER_QUEST_PROGRESS CASCADE CONSTRAINTS;
DROP TABLE LQ_USER_BADGE CASCADE CONSTRAINTS;
DROP TABLE LQ_REWARD_EXCHANGE CASCADE CONSTRAINTS;
DROP TABLE LQ_POINT_HISTORY CASCADE CONSTRAINTS;
DROP TABLE LQ_QUEST_REVIEW CASCADE CONSTRAINTS;
DROP TABLE LQ_USER_QUEST CASCADE CONSTRAINTS;
DROP TABLE LQ_QUEST_LOCATION CASCADE CONSTRAINTS;
DROP TABLE LQ_BUSINESS_INQUIRY CASCADE CONSTRAINTS;
DROP TABLE LQ_INQUIRY CASCADE CONSTRAINTS;
DROP TABLE LQ_NOTICE CASCADE CONSTRAINTS;
DROP TABLE LQ_FAQ CASCADE CONSTRAINTS;
DROP TABLE LQ_USER_RANK CASCADE CONSTRAINTS;
DROP TABLE LQ_LOCATION CASCADE CONSTRAINTS;
DROP TABLE LQ_REWARD_ITEM CASCADE CONSTRAINTS;
DROP TABLE LQ_BADGE CASCADE CONSTRAINTS;
DROP TABLE LQ_QUEST CASCADE CONSTRAINTS;
DROP TABLE LQ_BUSINESS CASCADE CONSTRAINTS;
DROP TABLE LQ_USER CASCADE CONSTRAINTS;
DROP TABLE LQ_QUEST_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE LQ_RECEIPT CASCADE CONSTRAINTS;

-- 독립 테이블
DROP TABLE LQ_LEVEL_RANGE CASCADE CONSTRAINTS;
DROP TABLE LQ_GRADE_RANGE CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_LQ_USER_PK;
DROP SEQUENCE SEQ_LQ_BUSINESS_PK;
DROP SEQUENCE SEQ_LQ_QUEST_PK;
DROP SEQUENCE SEQ_LQ_LOCATION_PK;
DROP SEQUENCE SEQ_LQ_QUEST_LOCATION_PK;
DROP SEQUENCE SEQ_LQ_USER_QUEST_PK;
DROP SEQUENCE SEQ_LQ_QUEST_REVIEW_PK;
DROP SEQUENCE SEQ_LQ_POINT_HISTORY_PK;
DROP SEQUENCE SEQ_LQ_REWARD_ITEM_PK;
DROP SEQUENCE SEQ_LQ_REWARD_EXCHANGE_PK;
DROP SEQUENCE SEQ_LQ_BADGE_PK;
DROP SEQUENCE SEQ_LQ_USER_BADGE_PK;
DROP SEQUENCE SEQ_LQ_USER_RANK_PK;
DROP SEQUENCE SEQ_LQ_BUSINESS_INQUIRY_PK;
DROP SEQUENCE SEQ_LQ_NOTICE_PK;
DROP SEQUENCE SEQ_LQ_FAQ_PK;
DROP SEQUENCE SEQ_LQ_INQUIRY_PK;
DROP SEQUENCE SEQ_LQ_USER_QUEST_PROGRESS_PK;
DROP SEQUENCE SEQ_LQ_LEVEL_RANGE_PK;
DROP SEQUENCE SEQ_LQ_GRADE_RANGE_PK;
DROP SEQUENCE SEQ_LQ_QUEST_CATEGORY_PK;
DROP SEQUENCE SEQ_LQ_RECEIPT_PK;