--시퀀스 먼저 생성
CREATE SEQUENCE SEQ_LQ_USER_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_BUSINESS_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_QUEST_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_LOCATION_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_QUEST_LOCATION_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_USER_QUEST_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_QUEST_REVIEW_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_POINT_HISTORY_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_REWARD_ITEM_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_REWARD_EXCHANGE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_BADGE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_USER_BADGE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_USER_RANK_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_BUSINESS_INQUIRY_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_NOTICE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_FAQ_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_INQUIRY_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_USER_QUEST_PROGRESS_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_LEVEL_RANGE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_GRADE_RANGE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_QUEST_CATEGORY_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_RECEIPT_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-----------------------------------------------------------------------------------
--테이블
CREATE TABLE LQ_USER (
    USER_ID       NUMBER PRIMARY KEY,
    USER_LOGIN_ID VARCHAR2(50) UNIQUE NOT NULL,
    NAME          VARCHAR2(50) NOT NULL,
    EMAIL         VARCHAR2(100) NOT NULL,
    PASSWORD      VARCHAR2(255) NOT NULL,
    NICKNAME      VARCHAR2(50) NOT NULL,
    BIRTH         DATE,
    GENDER        VARCHAR2(10),
    ROLE          VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    EXP           NUMBER DEFAULT 0 NOT NULL,
    POINT         NUMBER DEFAULT 0 NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UQ_LQ_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_LQ_USER_NICKNAME UNIQUE (NICKNAME),
    CONSTRAINT CHK_LQ_USER_ROLE CHECK (ROLE IN ('USER', 'BUSINESS', 'ADMIN')),
    CONSTRAINT CHK_LQ_USER_STATUS CHECK (STATUS IN ('ACTIVE', 'WITHDRAWN'))
);

CREATE TABLE LQ_BUSINESS (
    BUSINESS_ID     NUMBER PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    BUSINESS_NAME   VARCHAR2(100) NOT NULL,
    ZIP_CODE        VARCHAR2(10) NOT NULL,
    ADDRESS         VARCHAR2(255) NOT NULL,
    ADDRESS_DETAIL  VARCHAR2(255),
    PHONE           VARCHAR2(30),
    DESCRIPTION     VARCHAR2(500),
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UQ_LQ_BUSINESS_USER_ID UNIQUE (USER_ID),
    CONSTRAINT FK_LQ_BUSINESS_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID)
);


CREATE TABLE LQ_QUEST_CATEGORY(
    QUEST_CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE LQ_QUEST (
    QUEST_ID        NUMBER PRIMARY KEY,
    TITLE           VARCHAR2(100) NOT NULL,
    DESCRIPTION     VARCHAR2(1000) NOT NULL,
    CATEGORY        VARCHAR2(50) NOT NULL,
    REWARD_EXP      NUMBER DEFAULT 0 NOT NULL,
    REWARD_POINT    NUMBER DEFAULT 0 NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    TIME_LIMIT      NUMBER,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CHK_LQ_QUEST_STATUS
        CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'DELETED')),
    CONSTRAINT FK_LQ_QUEST_CATEGORY
        FOREIGN KEY (CATEGORY) REFERENCES LQ_QUEST_CATEGORY(CATEGORY_NAME)
);

CREATE TABLE LQ_REWARD_ITEM (
    REWARD_ITEM_ID   NUMBER PRIMARY KEY,
    NAME             VARCHAR2(100) NOT NULL,
    DESCRIPTION      VARCHAR2(1000),
    PRICE_POINT      NUMBER NOT NULL,
    STOCK            NUMBER DEFAULT 0 NOT NULL,
    STATUS           VARCHAR2(20) DEFAULT 'ON_SALE' NOT NULL,
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CHK_LQ_REWARD_ITEM_STATUS
        CHECK (STATUS IN ('ON_SALE', 'SOLD_OUT', 'HIDDEN')),
    CONSTRAINT CHK_LQ_REWARD_ITEM_PRICE CHECK (PRICE_POINT >= 0),
    CONSTRAINT CHK_LQ_REWARD_ITEM_STOCK CHECK (STOCK >= 0)
);

CREATE TABLE LQ_BADGE (
    BADGE_ID         NUMBER PRIMARY KEY,
    NAME             VARCHAR2(100) NOT NULL,
    DESCRIPTION      VARCHAR2(500),
    CONDITION_TEXT   VARCHAR2(500),
    ICON_URL         VARCHAR2(255),
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UQ_LQ_BADGE_NAME UNIQUE (NAME)
);

CREATE TABLE LQ_LOCATION (
    LOCATION_ID      NUMBER PRIMARY KEY,
    BUSINESS_ID      NUMBER,
    NAME             VARCHAR2(100) NOT NULL,
    ZIP_CODE        VARCHAR2(10) ,
    ADDRESS         VARCHAR2(255) ,
    ADDRESS_DETAIL  VARCHAR2(255),
    LATITUDE         NUMBER(10,7),
    LONGITUDE        NUMBER(10,7),
    LOCATION_TYPE    VARCHAR2(50),
    DESCRIPTION      VARCHAR2(500),
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_LOCATION_BUSINESS
        FOREIGN KEY (BUSINESS_ID) REFERENCES LQ_BUSINESS(BUSINESS_ID)
);

CREATE TABLE LQ_BUSINESS_INQUIRY (
    INQUIRY_ID      NUMBER PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    TITLE           VARCHAR2(200) NOT NULL,
    CONTENT         VARCHAR2(2000) NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_BUSINESS_INQUIRY_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT CHK_LQ_BUSINESS_INQUIRY_STATUS
        CHECK (STATUS IN ('PENDING', 'IN_PROGRESS', 'ANSWERED', 'CLOSED'))
);

CREATE TABLE LQ_QUEST_LOCATION (
    QUEST_LOCATION_ID   NUMBER PRIMARY KEY,
    QUEST_ID            NUMBER NOT NULL,
    LOCATION_ID         NUMBER NOT NULL,
    VISIT_ORDER         NUMBER NOT NULL,
    CREATED_AT          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_QUEST_LOCATION_QUEST
        FOREIGN KEY (QUEST_ID) REFERENCES LQ_QUEST(QUEST_ID),
    CONSTRAINT FK_LQ_QUEST_LOCATION_LOCATION
        FOREIGN KEY (LOCATION_ID) REFERENCES LQ_LOCATION(LOCATION_ID),
    CONSTRAINT CHK_LQ_QUEST_LOCATION_ORDER CHECK (VISIT_ORDER >= 1),
    CONSTRAINT UQ_LQ_QUEST_LOCATION_QUEST_LOC UNIQUE (QUEST_ID, LOCATION_ID),
    CONSTRAINT UQ_LQ_QUEST_LOCATION_ORDER UNIQUE (QUEST_ID, VISIT_ORDER)
);

CREATE TABLE LQ_USER_QUEST (
    USER_QUEST_ID    NUMBER PRIMARY KEY,
    USER_ID          NUMBER NOT NULL,
    QUEST_ID         NUMBER NOT NULL,
    STATUS           VARCHAR2(20) DEFAULT 'SAVED' NOT NULL,
    STARTED_AT       DATE,
    COMPLETED_AT     DATE,
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_USER_QUEST_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT FK_LQ_USER_QUEST_QUEST
        FOREIGN KEY (QUEST_ID) REFERENCES LQ_QUEST(QUEST_ID),
    CONSTRAINT UQ_LQ_USER_QUEST_USER_QUEST UNIQUE (USER_ID, QUEST_ID),
    CONSTRAINT CHK_LQ_USER_QUEST_STATUS
        CHECK (STATUS IN ('SAVED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED'))
);

CREATE TABLE LQ_USER_QUEST_PROGRESS (
    USER_QUEST_PROGRESS_ID   NUMBER PRIMARY KEY,
    USER_QUEST_ID            NUMBER NOT NULL,
    QUEST_LOCATION_ID        NUMBER NOT NULL,
    IS_COMPLETED             NUMBER(1) DEFAULT 0 NOT NULL,
    COMPLETED_AT             DATE,
    CONSTRAINT FK_LQ_UQP_USER_QUEST
        FOREIGN KEY (USER_QUEST_ID) REFERENCES LQ_USER_QUEST(USER_QUEST_ID),
    CONSTRAINT FK_LQ_UQP_QUEST_LOCATION
        FOREIGN KEY (QUEST_LOCATION_ID) REFERENCES LQ_QUEST_LOCATION(QUEST_LOCATION_ID),
    CONSTRAINT UQ_LQ_UQP_USER_QUEST_LOCATION
        UNIQUE (USER_QUEST_ID, QUEST_LOCATION_ID),
    CONSTRAINT CHK_LQ_UQP_IS_COMPLETED
        CHECK (IS_COMPLETED IN (0, 1))
);

CREATE TABLE LQ_QUEST_REVIEW (
    REVIEW_ID        NUMBER PRIMARY KEY,
    USER_ID          NUMBER NOT NULL,
    QUEST_ID      NUMBER NOT NULL,
    RATING           NUMBER NOT NULL,
    CONTENT          VARCHAR2(1000),
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_QUEST_REVIEW_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT FK_LQ_QUEST_REVIEW_QUEST
        FOREIGN KEY (QUEST_ID) REFERENCES LQ_QUEST(QUEST_ID),
    CONSTRAINT UQ_LQ_QUEST_REVIEW_USER_QUEST UNIQUE (USER_ID, QUEST_ID),
    CONSTRAINT CHK_LQ_QUEST_REVIEW_RATING CHECK (RATING BETWEEN 1 AND 5)
);

CREATE TABLE LQ_POINT_HISTORY (
    POINT_HISTORY_ID   NUMBER PRIMARY KEY,
    USER_ID            NUMBER NOT NULL,
    POINT_AMOUNT       NUMBER NOT NULL,
    CATEGORY           VARCHAR2(50) NOT NULL,
    DESCRIPTION        VARCHAR2(255) NOT NULL,
    CREATED_AT         DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_POINT_HISTORY_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID)
);

CREATE TABLE LQ_REWARD_EXCHANGE (
    EXCHANGE_ID       NUMBER PRIMARY KEY,
    USER_ID           NUMBER NOT NULL,
    REWARD_ITEM_ID    NUMBER NOT NULL,
    USED_POINT        NUMBER NOT NULL,
    STATUS            VARCHAR2(50),
    EXPIRED_AT        DATE,
    USED_AT           DATE,
    EXCHANGED_AT      DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LQ_REWARD_EXCHANGE_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT FK_LQ_REWARD_EXCHANGE_ITEM
        FOREIGN KEY (REWARD_ITEM_ID) REFERENCES LQ_REWARD_ITEM(REWARD_ITEM_ID),
    CONSTRAINT CHK_LQ_REWARD_EXCHANGE_USED_POINT CHECK (USED_POINT >= 0)
);

CREATE TABLE LQ_USER_BADGE (
    USER_BADGE_ID    NUMBER PRIMARY KEY,
    USER_ID          NUMBER NOT NULL,
    BADGE_ID         NUMBER NOT NULL,
    EARNED_AT        DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_USER_BADGE_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT FK_LQ_USER_BADGE_BADGE
        FOREIGN KEY (BADGE_ID) REFERENCES LQ_BADGE(BADGE_ID),
    CONSTRAINT UQ_LQ_USER_BADGE_USER_BADGE UNIQUE (USER_ID, BADGE_ID)
);

CREATE TABLE LQ_USER_RANK (
    RANK_ID         NUMBER PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    TOTAL_EXP       NUMBER DEFAULT 0 NOT NULL,
    RANKING         NUMBER NOT NULL,
    CONSTRAINT UQ_LQ_USER_RANK_USER UNIQUE (USER_ID),
    CONSTRAINT FK_LQ_USER_RANK_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT CHK_LQ_USER_RANK_EXP CHECK (TOTAL_EXP >= 0),
    CONSTRAINT CHK_LQ_USER_RANK_RANKING CHECK (RANKING >= 1)
);

CREATE TABLE LQ_NOTICE (
    NOTICE_ID      NUMBER PRIMARY KEY,
    TITLE          VARCHAR2(200) NOT NULL,
    CONTENT        VARCHAR2(4000) NOT NULL,
    VIEW_COUNT     NUMBER DEFAULT 0 NOT NULL,
    IS_PINNED      NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CHK_LQ_NOTICE_PINNED
        CHECK (IS_PINNED IN (0, 1))
);

CREATE TABLE LQ_FAQ (
    FAQ_ID          NUMBER PRIMARY KEY,
    CATEGORY        VARCHAR2(50) NOT NULL,
    QUESTION        VARCHAR2(500) NOT NULL,
    ANSWER          VARCHAR2(4000) NOT NULL,
    VIEW_COUNT      NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE LQ_INQUIRY (
    INQUIRY_ID         NUMBER PRIMARY KEY,
    USER_ID            NUMBER NOT NULL,
    TITLE              VARCHAR2(200) NOT NULL,
    CONTENT            VARCHAR2(4000) NOT NULL,
    STATUS             VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    ANSWER_CONTENT     VARCHAR2(4000),
    ANSWERED_AT        DATE,
    CREATED_AT         DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_INQUIRY_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT CHK_LQ_INQUIRY_STATUS
        CHECK (STATUS IN ('PENDING', 'ANSWERED'))
);

CREATE TABLE LQ_LEVEL_RANGE (
    LEVEL_ID NUMBER PRIMARY KEY,
    LEVEL_NO NUMBER NOT NULL,
    MIN_EXP NUMBER,
    MAX_EXP NUMBER
);

CREATE TABLE LQ_GRADE_RANGE(
    GRADE_ID NUMBER PRIMARY KEY,
    GRADE_NAME VARCHAR2(50) NOT NULL,
    MIN_LEVEL NUMBER,
    MAX_LEVEL NUMBER,
    ICON_URL VARCHAR2(4000)
);

CREATE TABLE LQ_RECEIPT (
    RECEIPT_ID               NUMBER PRIMARY KEY,
    USER_ID                  NUMBER NOT NULL,
    USER_QUEST_PROGRESS_ID   NUMBER NOT NULL,
    CATEGORY                 VARCHAR2(50) NOT NULL,
    VERIFY_STATUS            VARCHAR2(50) NOT NULL,
    FILE_PATH                VARCHAR2(4000) NOT NULL,
    FILE_UPLOAD_NAME         VARCHAR2(100),
    FILE_ORIGINAL_NAME       VARCHAR2(100),
    CREATED_AT               DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT FK_LQ_RECEIPT_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),

    CONSTRAINT FK_LQ_RECEIPT_UQP
        FOREIGN KEY (USER_QUEST_PROGRESS_ID)
        REFERENCES LQ_USER_QUEST_PROGRESS(USER_QUEST_PROGRESS_ID),

    CONSTRAINT FK_LQ_RECEIPT_CATEGORY
        FOREIGN KEY (CATEGORY)
        REFERENCES LQ_QUEST_CATEGORY(CATEGORY_NAME),

    CONSTRAINT CHK_LQ_RECEIPT_VERIFY_STATUS
        CHECK (VERIFY_STATUS IN ('SUCCESS', 'FAILED'))
);

-- 상점관리_삭제 제약조건 위반으로 제약조건 재설정
-- 1. 기존 제약조건 삭제
ALTER TABLE LQ_REWARD_ITEM DROP CONSTRAINT CHK_LQ_REWARD_ITEM_STATUS;

-- 2. 'DELETED'가 포함된 새로운 제약조건으로 재설정
ALTER TABLE LQ_REWARD_ITEM ADD CONSTRAINT CHK_LQ_REWARD_ITEM_STATUS 
    CHECK (STATUS IN ('ON_SALE', 'SOLD_OUT', 'HIDDEN', 'DELETED'));
