 --시퀀스 먼저 생성
CREATE SEQUENCE SEQ_LQ_USER_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_BUSINESS_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_QUEST_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_LOCATION_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_QUEST_LOCATION_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_USER_QUEST_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_QUEST_REVIEW_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_POINT_HISTORY_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_REWARD_ITEM_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_REWARD_EXCHANGE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_BADGE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_USER_BADGE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_USER_RANK_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_BUSINESS_INQUIRY_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_NOTICE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_FAQ_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_INQUIRY_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_USER_QUEST_PROGRESS_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_LEVEL_RANGE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_GRADE_RANGE_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_QUEST_CATEGORY_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_RECEIPT_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_USER_NOTIFICATION_SETTING_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_PUSH_SUBSCRIPTION_PK        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_NOTIFICATION_LOG_PK         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LQ_LOCATION_QR_PK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-----------------------------------------------------------------------------------
--테이블
CREATE TABLE LQ_USER (
    USER_ID       NUMBER PRIMARY KEY,
    USER_LOGIN_ID VARCHAR2(50) UNIQUE NOT NULL,
    NAME          VARCHAR2(50) NOT NULL,
    EMAIL         VARCHAR2(100) NOT NULL,
    PASSWORD      VARCHAR2(255) NOT NULL,
    NICKNAME      VARCHAR2(50) NOT NULL,
    BIRTH         DATE,
    GENDER        VARCHAR2(10),
    ROLE          VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    EXP           NUMBER DEFAULT 0 NOT NULL,
    POINT         NUMBER DEFAULT 0 NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UQ_LQ_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_LQ_USER_NICKNAME UNIQUE (NICKNAME),
    CONSTRAINT CHK_LQ_USER_ROLE CHECK (ROLE IN ('USER', 'BUSINESS', 'ADMIN')),
    CONSTRAINT CHK_LQ_USER_STATUS CHECK (STATUS IN ('ACTIVE', 'WITHDRAWN'))
);

CREATE TABLE LQ_BUSINESS (
    BUSINESS_ID     NUMBER PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    BUSINESS_NAME   VARCHAR2(100) NOT NULL,
    ZIP_CODE        VARCHAR2(10) NOT NULL,
    ADDRESS         VARCHAR2(255) NOT NULL,
    ADDRESS_DETAIL  VARCHAR2(255),
    PHONE           VARCHAR2(30),
    DESCRIPTION     VARCHAR2(500),
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UQ_LQ_BUSINESS_USER_ID UNIQUE (USER_ID),
    CONSTRAINT FK_LQ_BUSINESS_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID)
);


CREATE TABLE LQ_QUEST_CATEGORY(
    QUEST_CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE LQ_QUEST (
    QUEST_ID        NUMBER PRIMARY KEY,
    TITLE           VARCHAR2(100) NOT NULL,
    DESCRIPTION     VARCHAR2(1000) NOT NULL,
    CATEGORY        VARCHAR2(50) NOT NULL,
    REWARD_EXP      NUMBER DEFAULT 0 NOT NULL,
    REWARD_POINT    NUMBER DEFAULT 0 NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    TIME_LIMIT      NUMBER,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CHK_LQ_QUEST_STATUS
        CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'DELETED')),
    CONSTRAINT FK_LQ_QUEST_CATEGORY
        FOREIGN KEY (CATEGORY) REFERENCES LQ_QUEST_CATEGORY(CATEGORY_NAME)
);

CREATE TABLE LQ_REWARD_ITEM (
    REWARD_ITEM_ID   NUMBER PRIMARY KEY,
    NAME             VARCHAR2(100) NOT NULL,
    DESCRIPTION      VARCHAR2(1000),
    PRICE_POINT      NUMBER NOT NULL,
    STOCK            NUMBER DEFAULT 0 NOT NULL,
    STATUS           VARCHAR2(20) DEFAULT 'ON_SALE' NOT NULL,
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CHK_LQ_REWARD_ITEM_STATUS
        CHECK (STATUS IN ('ON_SALE', 'SOLD_OUT', 'HIDDEN')),
    CONSTRAINT CHK_LQ_REWARD_ITEM_PRICE CHECK (PRICE_POINT >= 0),
    CONSTRAINT CHK_LQ_REWARD_ITEM_STOCK CHECK (STOCK >= 0)
);

CREATE TABLE LQ_BADGE (
    BADGE_ID         NUMBER PRIMARY KEY,
    NAME             VARCHAR2(100) NOT NULL,
    DESCRIPTION      VARCHAR2(500),
    CONDITION_TEXT   VARCHAR2(500),
    ICON_URL         VARCHAR2(255),
    BADGE_CATEGORY   VARCHAR2(20) DEFAULT 'HABIT' NOT NULL,
    BADGE_DIFFICULTY VARCHAR2(10) DEFAULT 'EASY' NOT NULL,
    TRIGGER_TYPE     VARCHAR2(30) DEFAULT 'QUEST_COMPLETE' NOT NULL,
    DISPLAY_ORDER    NUMBER DEFAULT 0 NOT NULL,
    IS_ACTIVE        CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UQ_LQ_BADGE_NAME UNIQUE (NAME),
    CONSTRAINT CHK_LQ_BADGE_CATEGORY
        CHECK (BADGE_CATEGORY IN ('HABIT', 'EXPLORE', 'COMPLETE', 'BENEFIT')),
    CONSTRAINT CHK_LQ_BADGE_DIFFICULTY
        CHECK (BADGE_DIFFICULTY IN ('EASY', 'MID', 'HARD')),
    CONSTRAINT CHK_LQ_BADGE_TRIGGER_TYPE
        CHECK (TRIGGER_TYPE IN ('QUEST_COMPLETE', 'REVIEW_CREATE', 'REWARD_EXCHANGE')),
    CONSTRAINT CHK_LQ_BADGE_DISPLAY_ORDER
        CHECK (DISPLAY_ORDER >= 0),
    CONSTRAINT CHK_LQ_BADGE_IS_ACTIVE
        CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE TABLE LQ_LOCATION (
    LOCATION_ID      NUMBER PRIMARY KEY,
    BUSINESS_ID      NUMBER,
    NAME             VARCHAR2(100) NOT NULL,
    ZIP_CODE        VARCHAR2(10) ,
    ADDRESS         VARCHAR2(255) ,
    ADDRESS_DETAIL  VARCHAR2(255),
    LATITUDE         NUMBER(10,7),
    LONGITUDE        NUMBER(10,7),
    LOCATION_TYPE    VARCHAR2(50),
    DESCRIPTION      VARCHAR2(500),
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_LOCATION_BUSINESS
        FOREIGN KEY (BUSINESS_ID) REFERENCES LQ_BUSINESS(BUSINESS_ID)
);

CREATE TABLE LQ_BUSINESS_INQUIRY (
    INQUIRY_ID      NUMBER PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    TITLE           VARCHAR2(200) NOT NULL,
    CONTENT         VARCHAR2(2000) NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_BUSINESS_INQUIRY_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT CHK_LQ_BUSINESS_INQUIRY_STATUS
        CHECK (STATUS IN ('PENDING', 'IN_PROGRESS', 'ANSWERED', 'CLOSED'))
);

CREATE TABLE LQ_QUEST_LOCATION (
    QUEST_LOCATION_ID   NUMBER PRIMARY KEY,
    QUEST_ID            NUMBER NOT NULL,
    LOCATION_ID         NUMBER NOT NULL,
    VISIT_ORDER         NUMBER NOT NULL,
    CREATED_AT          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_QUEST_LOCATION_QUEST
        FOREIGN KEY (QUEST_ID) REFERENCES LQ_QUEST(QUEST_ID),
    CONSTRAINT FK_LQ_QUEST_LOCATION_LOCATION
        FOREIGN KEY (LOCATION_ID) REFERENCES LQ_LOCATION(LOCATION_ID),
    CONSTRAINT CHK_LQ_QUEST_LOCATION_ORDER CHECK (VISIT_ORDER >= 1),
    CONSTRAINT UQ_LQ_QUEST_LOCATION_QUEST_LOC UNIQUE (QUEST_ID, LOCATION_ID),
    CONSTRAINT UQ_LQ_QUEST_LOCATION_ORDER UNIQUE (QUEST_ID, VISIT_ORDER)
);

CREATE TABLE LQ_USER_QUEST (
    USER_QUEST_ID    NUMBER PRIMARY KEY,
    USER_ID          NUMBER NOT NULL,
    QUEST_ID         NUMBER NOT NULL,
    STATUS           VARCHAR2(20) DEFAULT 'SAVED' NOT NULL,
    STARTED_AT       DATE,
    DUE_AT           DATE,
    COMPLETED_AT     DATE,
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_USER_QUEST_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT FK_LQ_USER_QUEST_QUEST
        FOREIGN KEY (QUEST_ID) REFERENCES LQ_QUEST(QUEST_ID),
    CONSTRAINT UQ_LQ_USER_QUEST_USER_QUEST UNIQUE (USER_ID, QUEST_ID),
    CONSTRAINT CHK_LQ_USER_QUEST_STATUS
        CHECK (STATUS IN ('SAVED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED'))
);

CREATE TABLE LQ_USER_QUEST_PROGRESS (
    USER_QUEST_PROGRESS_ID   NUMBER PRIMARY KEY,
    USER_QUEST_ID            NUMBER NOT NULL,
    QUEST_LOCATION_ID        NUMBER NOT NULL,
    IS_COMPLETED             NUMBER(1) DEFAULT 0 NOT NULL,
    COMPLETED_AT             DATE,
    CONSTRAINT FK_LQ_UQP_USER_QUEST
        FOREIGN KEY (USER_QUEST_ID) REFERENCES LQ_USER_QUEST(USER_QUEST_ID),
    CONSTRAINT FK_LQ_UQP_QUEST_LOCATION
        FOREIGN KEY (QUEST_LOCATION_ID) REFERENCES LQ_QUEST_LOCATION(QUEST_LOCATION_ID),
    CONSTRAINT UQ_LQ_UQP_USER_QUEST_LOCATION
        UNIQUE (USER_QUEST_ID, QUEST_LOCATION_ID),
    CONSTRAINT CHK_LQ_UQP_IS_COMPLETED
        CHECK (IS_COMPLETED IN (0, 1))
);

CREATE TABLE LQ_QUEST_REVIEW (
    REVIEW_ID        NUMBER PRIMARY KEY,
    USER_ID          NUMBER NOT NULL,
    QUEST_ID      NUMBER NOT NULL,
    RATING           NUMBER NOT NULL,
    CONTENT          VARCHAR2(1000),
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_QUEST_REVIEW_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT FK_LQ_QUEST_REVIEW_QUEST
        FOREIGN KEY (QUEST_ID) REFERENCES LQ_QUEST(QUEST_ID),
    CONSTRAINT UQ_LQ_QUEST_REVIEW_USER_QUEST UNIQUE (USER_ID, QUEST_ID),
    CONSTRAINT CHK_LQ_QUEST_REVIEW_RATING CHECK (RATING BETWEEN 1 AND 5)
);

CREATE TABLE LQ_POINT_HISTORY (
    POINT_HISTORY_ID   NUMBER PRIMARY KEY,
    USER_ID            NUMBER NOT NULL,
    POINT_AMOUNT       NUMBER NOT NULL,
    CATEGORY           VARCHAR2(50) NOT NULL,
    DESCRIPTION        VARCHAR2(255) NOT NULL,
    CREATED_AT         DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_POINT_HISTORY_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID)
);

CREATE TABLE LQ_REWARD_EXCHANGE (
    EXCHANGE_ID       NUMBER PRIMARY KEY,
    USER_ID           NUMBER NOT NULL,
    REWARD_ITEM_ID    NUMBER NOT NULL,
    USED_POINT        NUMBER NOT NULL,
    STATUS            VARCHAR2(50),
    EXPIRED_AT        DATE,
    USED_AT           DATE,
    EXCHANGED_AT      DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LQ_REWARD_EXCHANGE_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT FK_LQ_REWARD_EXCHANGE_ITEM
        FOREIGN KEY (REWARD_ITEM_ID) REFERENCES LQ_REWARD_ITEM(REWARD_ITEM_ID),
    CONSTRAINT CHK_LQ_REWARD_EXCHANGE_USED_POINT CHECK (USED_POINT >= 0)
);

CREATE TABLE LQ_USER_BADGE (
    USER_BADGE_ID    NUMBER PRIMARY KEY,
    USER_ID          NUMBER NOT NULL,
    BADGE_ID         NUMBER NOT NULL,
    EARNED_AT        DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_USER_BADGE_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT FK_LQ_USER_BADGE_BADGE
        FOREIGN KEY (BADGE_ID) REFERENCES LQ_BADGE(BADGE_ID),
    CONSTRAINT UQ_LQ_USER_BADGE_USER_BADGE UNIQUE (USER_ID, BADGE_ID)
);

CREATE TABLE LQ_USER_RANK (
    RANK_ID         NUMBER PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    TOTAL_EXP       NUMBER DEFAULT 0 NOT NULL,
    RANKING         NUMBER NOT NULL,
    CONSTRAINT UQ_LQ_USER_RANK_USER UNIQUE (USER_ID),
    CONSTRAINT FK_LQ_USER_RANK_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT CHK_LQ_USER_RANK_EXP CHECK (TOTAL_EXP >= 0),
    CONSTRAINT CHK_LQ_USER_RANK_RANKING CHECK (RANKING >= 1)
);

CREATE TABLE LQ_NOTICE (
    NOTICE_ID      NUMBER PRIMARY KEY,
    TITLE          VARCHAR2(200) NOT NULL,
    CONTENT        VARCHAR2(4000) NOT NULL,
    VIEW_COUNT     NUMBER DEFAULT 0 NOT NULL,
    IS_PINNED      NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CHK_LQ_NOTICE_PINNED
        CHECK (IS_PINNED IN (0, 1))
);

CREATE TABLE LQ_FAQ (
    FAQ_ID          NUMBER PRIMARY KEY,
    CATEGORY        VARCHAR2(50) NOT NULL,
    QUESTION        VARCHAR2(500) NOT NULL,
    ANSWER          VARCHAR2(4000) NOT NULL,
    VIEW_COUNT      NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE LQ_INQUIRY (
    INQUIRY_ID         NUMBER PRIMARY KEY,
    USER_ID            NUMBER NOT NULL,
    TITLE              VARCHAR2(200) NOT NULL,
    CONTENT            VARCHAR2(4000) NOT NULL,
    STATUS             VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    ANSWER_CONTENT     VARCHAR2(4000),
    ANSWERED_AT        DATE,
    CREATED_AT         DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LQ_INQUIRY_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
    CONSTRAINT CHK_LQ_INQUIRY_STATUS
        CHECK (STATUS IN ('PENDING', 'ANSWERED'))
);

CREATE TABLE LQ_LEVEL_RANGE (
    LEVEL_ID NUMBER PRIMARY KEY,
    LEVEL_NO NUMBER NOT NULL,
    MIN_EXP NUMBER,
    MAX_EXP NUMBER
);

CREATE TABLE LQ_GRADE_RANGE(
    GRADE_ID NUMBER PRIMARY KEY,
    GRADE_NAME VARCHAR2(50) NOT NULL,
    MIN_LEVEL NUMBER,
    MAX_LEVEL NUMBER,
    ICON_URL VARCHAR2(4000)
);

CREATE TABLE LQ_RECEIPT (
    RECEIPT_ID               NUMBER PRIMARY KEY,
    USER_ID                  NUMBER NOT NULL,
    USER_QUEST_PROGRESS_ID   NUMBER NOT NULL,
    CATEGORY                 VARCHAR2(50) NOT NULL,
    VERIFY_STATUS            VARCHAR2(50) NOT NULL,
    FILE_PATH                VARCHAR2(4000) NOT NULL,
    FILE_UPLOAD_NAME         VARCHAR2(100),
    FILE_ORIGINAL_NAME       VARCHAR2(100),
    CREATED_AT               DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT FK_LQ_RECEIPT_USER
        FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),

    CONSTRAINT FK_LQ_RECEIPT_UQP
        FOREIGN KEY (USER_QUEST_PROGRESS_ID)
        REFERENCES LQ_USER_QUEST_PROGRESS(USER_QUEST_PROGRESS_ID),

    CONSTRAINT FK_LQ_RECEIPT_CATEGORY
        FOREIGN KEY (CATEGORY)
        REFERENCES LQ_QUEST_CATEGORY(CATEGORY_NAME),

    CONSTRAINT CHK_LQ_RECEIPT_VERIFY_STATUS
        CHECK (VERIFY_STATUS IN ('SUCCESS', 'FAILED'))
);

-- 1) 사용자 알림 설정
CREATE TABLE LQ_USER_NOTIFICATION_SETTING (
SETTING_ID NUMBER NOT NULL,
USER_ID NUMBER NOT NULL,
PUSH_AGREE CHAR(1) DEFAULT 'N' NOT NULL,
MARKETING_AGREE CHAR(1) DEFAULT 'N' NOT NULL,
LUNCH_PUSH_AGREE CHAR(1) DEFAULT 'N' NOT NULL,
DINNER_PUSH_AGREE CHAR(1) DEFAULT 'N' NOT NULL,
WEEKEND_PUSH_AGREE CHAR(1) DEFAULT 'N' NOT NULL,
PREFERRED_TIMEZONE VARCHAR2(50),
UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

CONSTRAINT PK_LQ_USER_NOTIFICATION_SETTING PRIMARY KEY (SETTING_ID),
CONSTRAINT UQ_LQ_UNS_USER UNIQUE (USER_ID),
CONSTRAINT FK_LQ_UNS_USER FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),

CONSTRAINT CHK_LQ_UNS_PUSH_AGREE CHECK (PUSH_AGREE IN ('Y', 'N')),
CONSTRAINT CHK_LQ_UNS_MARKETING_AGREE CHECK (MARKETING_AGREE IN ('Y', 'N')),
CONSTRAINT CHK_LQ_UNS_LUNCH_AGREE CHECK (LUNCH_PUSH_AGREE IN ('Y', 'N')),
CONSTRAINT CHK_LQ_UNS_DINNER_AGREE CHECK (DINNER_PUSH_AGREE IN ('Y', 'N')),
CONSTRAINT CHK_LQ_UNS_WEEKEND_AGREE CHECK (WEEKEND_PUSH_AGREE IN ('Y', 'N'))
);

-- 2) 웹 푸시 구독 정보
CREATE TABLE LQ_PUSH_SUBSCRIPTION (
SUBSCRIPTION_ID NUMBER NOT NULL,
USER_ID NUMBER NOT NULL,
ENDPOINT VARCHAR2(2000) NOT NULL,
P256DH_KEY VARCHAR2(500) NOT NULL,
AUTH_KEY VARCHAR2(500) NOT NULL,
DEVICE_TYPE VARCHAR2(30),
BROWSER_NAME VARCHAR2(30),
USER_AGENT VARCHAR2(1000),
IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
LAST_SUCCESS_AT DATE,
LAST_FAIL_AT DATE,
FAIL_COUNT NUMBER DEFAULT 0 NOT NULL,
CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,

CONSTRAINT PK_LQ_PUSH_SUBSCRIPTION PRIMARY KEY (SUBSCRIPTION_ID),
CONSTRAINT FK_LQ_PS_USER FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
CONSTRAINT UQ_LQ_PS_USER_ENDPOINT UNIQUE (USER_ID, ENDPOINT),

CONSTRAINT CHK_LQ_PS_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
CONSTRAINT CHK_LQ_PS_FAIL_COUNT CHECK (FAIL_COUNT >= 0),
CONSTRAINT CHK_LQ_PS_DEVICE_TYPE CHECK (DEVICE_TYPE IS NULL OR DEVICE_TYPE IN ('PC', 'MOBILE'))
);

-- 3) 알림 발송/클릭 로그
CREATE TABLE LQ_NOTIFICATION_LOG (
NOTIFICATION_ID NUMBER NOT NULL,
USER_ID NUMBER NOT NULL,
SUBSCRIPTION_ID NUMBER,
NOTIFICATION_TYPE VARCHAR2(20) NOT NULL,
TITLE VARCHAR2(200) NOT NULL,
BODY VARCHAR2(500) NOT NULL,
TARGET_URL VARCHAR2(500),
SEND_STATUS VARCHAR2(20) NOT NULL,
FAIL_REASON VARCHAR2(500),
SENT_AT DATE NOT NULL,
CLICKED_AT DATE,
CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

CONSTRAINT PK_LQ_NOTIFICATION_LOG PRIMARY KEY (NOTIFICATION_ID),
CONSTRAINT FK_LQ_NL_USER FOREIGN KEY (USER_ID) REFERENCES LQ_USER(USER_ID),
CONSTRAINT FK_LQ_NL_SUBSCRIPTION FOREIGN KEY (SUBSCRIPTION_ID)
REFERENCES LQ_PUSH_SUBSCRIPTION(SUBSCRIPTION_ID),

CONSTRAINT CHK_LQ_NL_TYPE CHECK (NOTIFICATION_TYPE IN ('LUNCH', 'DINNER', 'WEEKEND')),
CONSTRAINT CHK_LQ_NL_STATUS CHECK (SEND_STATUS IN ('SUCCESS', 'FAIL', 'SKIPPED')),
CONSTRAINT CHK_LQ_NL_CLICK_TIME CHECK (CLICKED_AT IS NULL OR CLICKED_AT >= SENT_AT)
);

CREATE TABLE LQ_LOCATION_QR (
    QR_ID           NUMBER PRIMARY KEY,
    LOCATION_ID     NUMBER NOT NULL,
    QR_AUTH_KEY     VARCHAR2(255) UNIQUE,
    QR_IMAGE_URL    VARCHAR2(500),
    IS_ACTIVE       NUMBER(1) DEFAULT 1,
    CREATED_AT      DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LQ_QR_LOCATION
        FOREIGN KEY (LOCATION_ID) REFERENCES LQ_LOCATION(LOCATION_ID),
    CONSTRAINT CHK_LQ_QR_ACTIVE
        CHECK (IS_ACTIVE IN (0, 1))
);

/* 7. 비즈니스 인증 로그 테이블 추가 */
CREATE TABLE LQ_BUSINESS_AUTH_LOG (
    AUTH_LOG_ID      NUMBER PRIMARY KEY,
    BUSINESS_ID      NUMBER NOT NULL,
    LOCATION_ID      NUMBER NOT NULL,
    USER_ID          NUMBER NOT NULL,
    AUTH_TYPE        VARCHAR2(20),
    PAYMENT_AMOUNT   NUMBER DEFAULT 0,
    SETTLEMENT_AMT   NUMBER DEFAULT 0,
    CREATED_AT       DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LOG_BIZ
        FOREIGN KEY (BUSINESS_ID) REFERENCES LQ_BUSINESS(BUSINESS_ID),
    CONSTRAINT FK_LOG_LOC
        FOREIGN KEY (LOCATION_ID) REFERENCES LQ_LOCATION(LOCATION_ID)
);


/* 8. 정산용 시퀀스/테이블 추가 */
CREATE SEQUENCE SEQ_LQ_SETTLEMENT_PK
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE LQ_SETTLEMENT (
    SETTLEMENT_ID    NUMBER PRIMARY KEY,
    BUSINESS_ID      NUMBER NOT NULL,
    SETTLEMENT_MONTH CHAR(6) NOT NULL,
    TOTAL_QR_COUNT   NUMBER DEFAULT 0,
    TOTAL_RCP_COUNT  NUMBER DEFAULT 0,
    GROSS_AMOUNT     NUMBER DEFAULT 0,
    SERVICE_FEE      NUMBER DEFAULT 0,
    NET_AMOUNT       NUMBER DEFAULT 0,
    STATUS           VARCHAR2(20) DEFAULT 'PENDING',
    CREATED_AT       DATE DEFAULT SYSDATE,
    CONSTRAINT FK_SETTLE_BIZ
        FOREIGN KEY (BUSINESS_ID) REFERENCES LQ_BUSINESS(BUSINESS_ID)
);

ALTER TABLE LQ_REWARD_ITEM DROP CONSTRAINT CHK_LQ_REWARD_ITEM_STATUS;

-- 2. 'DELETED'가 포함된 새로운 제약조건으로 재설정
ALTER TABLE LQ_REWARD_ITEM ADD CONSTRAINT CHK_LQ_REWARD_ITEM_STATUS 
    CHECK (STATUS IN ('ON_SALE', 'SOLD_OUT', 'HIDDEN', 'DELETED'));
    
ALTER TABLE LQ_USER_QUEST DROP CONSTRAINT UQ_LQ_USER_QUEST_USER_QUEST;

/* 2. LQ_BUSINESS_INQUIRY 확장 */
ALTER TABLE LQ_BUSINESS_INQUIRY ADD (
    ZIP_CODE        VARCHAR2(10),
    ADDRESS         VARCHAR2(255),
    ADDRESS_DETAIL  VARCHAR2(255),
    PHONE           VARCHAR2(30)
);

ALTER TABLE LQ_BUSINESS_INQUIRY ADD (
    LATITUDE        NUMBER(10,7),
    LONGITUDE       NUMBER(10,7),
    LOCATION_TYPE   VARCHAR2(50)
);


/* 3. LQ_BUSINESS 확장 */
ALTER TABLE LQ_BUSINESS ADD (
    SOURCE_INQUIRY_ID    NUMBER,
    QR_VISIT_COUNT       NUMBER DEFAULT 0,
    RECEIPT_AUTH_COUNT   NUMBER DEFAULT 0,
    TOTAL_REVENUE        NUMBER DEFAULT 0,
    TOTAL_SALES_AMOUNT   NUMBER DEFAULT 0
);


/* 4. LQ_LOCATION 확장 */
ALTER TABLE LQ_LOCATION ADD (
    QR_VISIT_COUNT       NUMBER DEFAULT 0,
    RECEIPT_AUTH_COUNT   NUMBER DEFAULT 0
);

ALTER TABLE LQ_LOCATION
MODIFY LOCATION_TYPE VARCHAR2(50) NOT NULL;

ALTER TABLE LQ_LOCATION
ADD CONSTRAINT CHK_LQ_LOCATION_TYPE
CHECK (LOCATION_TYPE IN ('VISIT', 'EXPERIENCE', 'PURCHASE'));

ALTER TABLE LQ_LOCATION DROP CONSTRAINT CHK_LQ_LOCATION_TYPE;
ALTER TABLE LQ_LOCATION MODIFY LOCATION_TYPE VARCHAR2(50);

ALTER TABLE LQ_LOCATION
ADD LOCATION_CATEGORY VARCHAR2(20);

UPDATE LQ_LOCATION
SET LOCATION_CATEGORY = 'VISIT'
WHERE LOCATION_CATEGORY IS NULL;

ALTER TABLE LQ_LOCATION
MODIFY LOCATION_CATEGORY VARCHAR2(20) NOT NULL;

ALTER TABLE LQ_LOCATION
ADD CONSTRAINT CHK_LQ_LOCATION_CATEGORY
CHECK (LOCATION_CATEGORY IN ('VISIT', 'EXPERIENCE', 'PURCHASE'));

ALTER TABLE LQ_QUEST
DROP CONSTRAINT FK_LQ_QUEST_CATEGORY;

ALTER TABLE LQ_RECEIPT
DROP CONSTRAINT FK_LQ_RECEIPT_CATEGORY;

DROP TABLE LQ_QUEST_CATEGORY;
ALTER TABLE LQ_QUEST DROP COLUMN CATEGORY;
ALTER TABLE LQ_RECEIPT DROP COLUMN CATEGORY;

-- QR 부분
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'LQ_LOCATION'
      AND COLUMN_NAME = 'LOCATION_CATEGORY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE LQ_LOCATION ADD (LOCATION_CATEGORY VARCHAR2(20))';
    END IF;
END;
/

UPDATE LQ_LOCATION
SET LOCATION_CATEGORY = CASE
    WHEN LOCATION_TYPE IN ('VISIT', 'EXPERIENCE', 'PURCHASE') THEN LOCATION_TYPE
    ELSE 'VISIT'
END
WHERE LOCATION_CATEGORY IS NULL;

COMMIT;
